### ISSUE TITLE
Cholesterol likelihood

### ISSUE THREAD

**Issue by Angelica-Pulido** [NutaM/Historical_recipes#6]
Hi,

I just would like to raise a concern about the number of eggs we're scrambling
Would it be any risk of having a cholesterol attack after this breakfast? 

best,

Angelica

**Comment by NutaM** [comment]
Sounds great! Do you want to eat it anyway?

Regards,
Anna

**Comment by Angelica-Pulido** [comment]
sure!

eggs are eggs after all, right?! :P

**Comment by NutaM** [comment]
#2 and go to the trening;)

regards
Anna
